config/routes.rb
Rails.application.routes.draw do

  
  resources :allot_leaves do
    resources :employee_leaves
  end
  resources :leave_heads
  resources :paymonths do 
    resources :paymonth_leaves
  end
  resources :salary_structures
   resources :employees
   resources :departments
   resources :designations
   resources :employee_salaries

  
  root 'employees#index'

end

app/models/allot_leave.rb
class AllotLeave < ActiveRecord::Base
	belongs_to :employee
	belongs_to :paymonth
	has_many :employee_leaves

	validate :checking

	def checking
		if !(AllotLeave.where("employee_id =? AND paymonth_id = ?",self.employee_id, self.paymonth_id).empty? )
			errors.add(:employee_id ,"Leave Structure Already exist for this date")
		end
	end

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :states
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :employees
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/designation.rb
class Designation < ActiveRecord::Base
	has_many :employees
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :allot_leaves
	belongs_to :department
	belongs_to :designation
	has_many :employee_salaries
	validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
	validates_format_of :address, :with => /\A[^`!@#\$%\^&*+_=]+\z/
	validates_presence_of :name,:dob,:address,:designation_id,:department_id,:gender,:state
	validate :validate_birth, if: :date_of_joining?

	def validate_birth
		if  !(self.date_of_joining.nil?)
			if !(self.date_of_joining > self.dob+20.years )
				errors.add(:dob, "Employee should be 20 yesrs old")
			end
			if !(self.date_of_joining < Date.today )
				errors.add(:date_of_joining, "Joining Date should be less than todays date ")
			end
		end

		if (Paymonth.where("month_year =? AND month_name =?",self.salary_date.year,self.salary_date.strftime("%b")).empty?)
			errors.add(:salary_date, "Salary Does not Belong to any Pay month ")
		end
	end
end

app/models/employee_leave.rb
class EmployeeLeave < ActiveRecord::Base
	belongs_to :allot_leave
	belongs_to :paymonth_leave
	validates_presence_of :head_values
end

app/models/employee_salary.rb
class EmployeeSalary < ActiveRecord::Base

	belongs_to :employee
	belongs_to :salary_structure
	validates_presence_of :salary_structure_id,:employee_id
	validate :salary_date, if: :salary_date?
	

	def salary_date
		if !self.employee_id.nil? && !self.salary_date.nil? && !self.salary_structure_id.nil?
			@employee= Employee.where("id =?",self.employee_id).first
			if (self.salary_date < @employee.date_of_joining)
				errors.add(:salary_date, "Date is invalid. Should not be greater than #{@employee.date_of_joining}")
			end

			@salaries = @employee.employee_salaries

			for salary in @salaries
				if(salary.salary_date.month == self.salary_date.month && salary.salary_date.year == self.salary_date.year)

					errors.add(:salary_date, "Date is invalid. Salary Slip already exsits")
				end
			end
		end
	end
	


end

app/models/leave_head.rb
class LeaveHead < ActiveRecord::Base
	has_many :paymonth_leaves
	has_many :paymonths, through: :paymonth_leaves
end

app/models/paymonth.rb
class Paymonth < ActiveRecord::Base
	has_many :allot_leaves
	has_many :paymonth_leaves
	has_many :leave_heads, through: :paymonth_leaves
	before_save :determine
	validate :months

	def determine
		date = self.pay_month
		self.month_year = @date.year
		self.day_count = Time.days_in_month(self.pay_month.month,self.pay_month.year)
		self.month_name = date.strftime("%b")
		if (Paymonth.where("month_year =? AND month_name =?",self.month_year,self.month_name))
			errors.add(:pay_month, "Pay Month already exsits")
		end
	end

	def months
		date = self.pay_month
		if !(Paymonth.where("month_year =? AND month_name =?",date.year,date.strftime("%b")).empty?)
			errors.add(:pay_month, "Pay Month already exsits")
		end
	end
end

app/models/paymonth_leave.rb
class PaymonthLeave < ActiveRecord::Base
	belongs_to :paymonth
	belongs_to :leave_head
	has_many :employee_leaves
end

app/models/salary_structure.rb
class SalaryStructure < ActiveRecord::Base
	has_many :employee_salaries
	validates_presence_of :name,:basic, :da, :hra, :others,:conveyance, :special_allowance
	#validates_numericality_of :basic, :da, :hra, :others,:conveyance, :special_allowance
	before_save :calculate
	
	def calculate
		@basic_da= self.basic+self.da
		self.pf=(@basic_da*12)/100
		self.emp_pf=(@basic_da*5)/100
		self.gross=self.basic+self.da+self.hra+self.special_allowance+self.others+self.conveyance

		if (self.gross > 15000)
			self.pt=200
			self.gratuity =200
		else
			self.pt=100
			self.gratuity =100
		end
		self.monthly_ctc=self.emp_pf+self.gross+self.pt
	end
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :country
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def index
  	@employees=Employee.all
	end

	def new
		@employee=Employee.new
    @states=State.all
	end

  def show
    @employee=Employee.find(params[:id])
    @employee_salaries=@employee.employee_salaries
  end

  def edit
    @employee=Employee.find(params[:id])
  end


	def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path(), notice: 'Employee was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    @employee=Employee.find(params[:id])
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_path, notice: 'Employee was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @employee=Employee.find(params[:id])
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_path, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  	def employee_params
      params.require(:employee).permit(:name, :dob, :gender, :address, :designation_id, :department_id, :date_of_joining, :state,:salary_date)
    end


end

app/controllers/paymonths_controller.rb
class PaymonthsController < ApplicationController
  before_action :set_paymonth, only: [:show, :edit, :update, :destroy]


  def index
    @paymonths = Paymonth.all
     @paymonth = Paymonth.new
  end

  def show
  end

  def new
    @paymonth = Paymonth.new
  end

  def edit
  end

  def create
    @paymonth = Paymonth.new(paymonth_params)

    respond_to do |format|
      if @paymonth.save
        format.html { redirect_to paymonths_path notice: 'Paymonth was successfully created.' }
        format.json { render :show, status: :created, location: @paymonth }
      else
        format.html { render :new }
        format.json { render json: @paymonth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paymonths/1
  # PATCH/PUT /paymonths/1.json
  def update
    respond_to do |format|
      if @paymonth.update(paymonth_params)
        format.html { redirect_to @paymonth, notice: 'Paymonth was successfully updated.' }
        format.json { render :show, status: :ok, location: @paymonth }
      else
        format.html { render :edit }
        format.json { render json: @paymonth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paymonths/1
  # DELETE /paymonths/1.json
  def destroy
    @paymonth.destroy
    respond_to do |format|
      format.html { redirect_to paymonths_url, notice: 'Paymonth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paymonth
      @paymonth = Paymonth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paymonth_params
      params.require(:paymonth).permit(:month_year, :day_count, :month_name, :pay_month )
    end
end

app/helpers/allot_leaves_helper.rb
module AllotLeavesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/designation_helper.rb
module DesignationHelper
end

app/helpers/employee_leaves_helper.rb
module EmployeeLeavesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/leave_heads_helper.rb
module LeaveHeadsHelper
end

app/helpers/paymonth_leaves_helper.rb
module PaymonthLeavesHelper
end

app/helpers/paymonths_helper.rb
module PaymonthsHelper
end

app/views/employees/_form.html.erb
</script>
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :Name %>
      <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "Enter Name"%>
    </div>
    <div class="col-md-6">
      <%= f.label :Address %>
      <%= f.text_area :address, class: "form-control",placeholder: "Enter Address"%>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :Date_Of_Birth %>
      <%= f.text_field :dob, class: "form-control",placeholder: "Enter Date Of Birth", id:"datepicker" %>
    </div>
    <div class="col-md-6">
      <%= f.label :Date_of_Joining %>
      <%= f.text_field :date_of_joining, class: "form-control",placeholder: "Enter Date Of joining", id:"datepicker2" %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-6">
     <%= f.label :Designation %>
      <%= f.select :designation_id, Designation.all.map { |u| [u.name, u.id] },
                                            { include_blank: true },
                                            { class: "chosen-select" }%>
    </div>
    <div class="col-md-6">
      <%= f.label :Department %>
      <%= f.select :department_id, Department.all.map { |u| [u.name, u.id] },
                                            { include_blank: true },
                                            { class: "chosen-select" }%>
      
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :Gender %>
      <%= f.select :gender, options_for_select(["Male", "Female"]),
                          { include_blank: true },
                          { class: "chosen-select" }%> 
    </div>
    
    
    <div class="col-md-6">
      <%= f.label :state %>
      <%= f.select :state, State.all.map { |u| [u.name, u.id] },
                                            { include_blank: true },
                                            { id: "state" }%> 
    </div>
  </div>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <%= f.label :Date_of_Salary %>
        <%= f.text_field :salary_date, class: "form-control",placeholder: "Enter Salary Date", id:"datepicker1" %>
    </div>
  </div>
  
  <br/>
  <br/>
  <%= f.submit class:"btn btn-info btn-fixi" %>
<%end%>

app/views/employees/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
				<div class="panel-heading">Edit Employees</div>
				<div class="panel-body">
					<%=render 'form'%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/employees/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
		  	<div class="panel-heading">Listing Employees</div>
		  	<div class="panel-body">
		  		<table class="table table-bordered", id="myTable">
		        <thead>
		          <tr>
		            <th>Name</th>
		            <th>Gender</th>
		            <th>Designation</th>
		            <th>Department</th>
		            <th>D.O.J</th>
		            <th>Salary Date</th>
		            <th>Actions</th>

		          </tr>
		        </thead>

		        <tbody>
		          <% @employees.each do |employee| %>
		            <tr>
		              <td><%=link_to employee.name, employee_path(employee) %></td>
		              <td><%= employee.gender%></td>
		              <td><%= employee.designation.name%></td>
		              <td><%= employee.department.name%></td>
		              <td><%= employee.date_of_joining.strftime("%d %b %y") %></td>
		              <td><%= employee.salary_date.strftime("%d %b %y") %></td>
		              <td><%= link_to 'Show', employee_path(employee) %>
                      <%= link_to 'Edit', edit_employee_path(employee) %>
                      <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		             </tr>
		          <% end %>
		        </tbody>
		      </table>
		    </div>
		  </div>
		</div>
	</div>
</div>

app/views/employees/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
				<div class="panel-heading">Add Employees</div>
				<div class="panel-body">
					<%=render 'form'%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/employees/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
		  	<div class="panel-heading">Listing Saalary Slips</div>
		  	<div class="panel-body">
		  		<table class="table table-bordered", id="myTable">
		        <thead>
		          <tr>
		            <th>Employee Name</th>
		            <th>Salary Date</th>
		            <th>Basic </th>
		            <th>Dearness Allowances</th>
		            <th>House Rent Allowances</th>
		            <th>Gross</th>
		            <th>Momthly Ctc</th>
		          </tr>
		        </thead>

		        <tbody>
		          <% @employee_salaries.each do |employee| %>
		            <tr>
		              <td><%=link_to employee.employee.name , employee_salary_path(employee)%></td>
		              <td><%= employee.salary_date.strftime("%b %y") %></td>
		              <td><%= employee.salary_structure.basic%></td>
		              <td><%= employee.salary_structure.da%></td>
		              <td><%= employee.salary_structure.hra%></td>
		              <td><%= employee.salary_structure.gross%></td>
		              <td><%= employee.salary_structure.monthly_ctc%></td>
		             </tr>
		          <% end %>
		        </tbody>
		      </table>
		    </div>
		  </div>
		</div>
	</div>
</div>

app/views/paymonths/_form.html.erb
<%= form_for(@paymonth) do |f| %>
  <% if @paymonth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paymonth.errors.count, "error") %> prohibited this paymonth from being saved:</h2>

      <ul>
      <% @paymonth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pay_month %><br>
    <%= f.text_field :pay_month, class: "form-control",placeholder: "Enter Date Of Birth", id:"datepicker1"  %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/paymonths/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
				<div class="panel-heading">Edit PayMonth</div>
				<div class="panel-body">
					<%=render 'form'%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/paymonths/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">Add Pay Month</div>
        <div class="panel-body">
          <%= form_for(@paymonth) do |f| %>
  <% if @paymonth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paymonth.errors.count, "error") %> prohibited this paymonth from being saved:</h2>

      <ul>
      <% @paymonth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pay_month %><br>
    <%= f.text_field :pay_month, class: "form-control",placeholder: "Enter Date Of Birth", id:"datepicker1"  %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
      <div class="panel panel-info">
        <div class="panel-heading">Listing Employees</div>
        <div class="panel-body">
          <table class="table table-bordered", id="myTable">
            <thead>
              <tr>
                <th>Month year</th>
                <th>Day count</th>
                <th>Month name</th>
                <th>Pay month</th>
                <th >Actions</th>
              </tr>
            </thead>

            <tbody>
              <% @paymonths.each do |paymonth| %>
                <tr>
                  <td><%= paymonth.month_year %></td>
                  <td><%= paymonth.day_count %></td>
                  <td><%= paymonth.month_name %></td>
                  <td><%= paymonth.pay_month %></td>
                  <td><%= link_to 'Destroy', paymonth, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <%= link_to 'Add Leave Heads', paymonth_paymonth_leaves_path(paymonth) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/paymonths/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
				<div class="panel-heading">Add Pay Month</div>
				<div class="panel-body">
					<%=render 'form'%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/paymonths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month year:</strong>
  <%= @paymonth.month_year %>
</p>

<p>
  <strong>Day count:</strong>
  <%= @paymonth.day_count %>
</p>

<p>
  <strong>Month name:</strong>
  <%= @paymonth.month_name %>
</p>

<p>
  <strong>Pay month:</strong>
  <%= @paymonth.pay_month %>
</p>

<%= link_to 'Edit', edit_paymonth_path(@paymonth) %> |
<%= link_to 'Back', paymonths_path %>