config/routes.rb
Rails.application.routes.draw do

  
  resources :allot_leaves do
    resources :employee_leaves
  end
  resources :leave_heads
  resources :paymonths do 
    resources :paymonth_leaves
  end
  resources :salary_structures
   resources :employees
   resources :departments
   resources :designations
   resources :employee_salaries

  
  root 'employees#index'

end

app/models/allot_leave.rb
class AllotLeave < ActiveRecord::Base
	belongs_to :employee
	belongs_to :paymonth
	has_many :employee_leaves

	validate :checking

	def checking
		if !(AllotLeave.where("employee_id =? AND paymonth_id = ?",self.employee_id, self.paymonth_id).empty? )
			errors.add(:employee_id ,"Leave Structure Already exist for this date")
		end
	end

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :states
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :employees
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/designation.rb
class Designation < ActiveRecord::Base
	has_many :employees
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :allot_leaves
	belongs_to :department
	belongs_to :designation
	has_many :employee_salaries
	validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
	validates_format_of :address, :with => /\A[^`!@#\$%\^&*+_=]+\z/
	validates_presence_of :name,:dob,:address,:designation_id,:department_id,:gender,:state
	validate :validate_birth, if: :date_of_joining?

	def validate_birth
		if  !(self.date_of_joining.nil?)
			if !(self.date_of_joining > self.dob+20.years )
				errors.add(:dob, "Employee should be 20 yesrs old")
			end
			if !(self.date_of_joining < Date.today )
				errors.add(:date_of_joining, "Joining Date should be less than todays date ")
			end
		end

		if (Paymonth.where("month_year =? AND month_name =?",self.salary_date.year,self.salary_date.strftime("%b")).empty?)
			errors.add(:salary_date, "Salary Does not Belong to any Pay month ")
		end
	end
end

app/models/employee_leave.rb
class EmployeeLeave < ActiveRecord::Base
	belongs_to :allot_leave
	belongs_to :paymonth_leave
	validates_presence_of :head_values
end

app/models/employee_salary.rb
class EmployeeSalary < ActiveRecord::Base

	belongs_to :employee
	belongs_to :salary_structure
	validates_presence_of :salary_structure_id,:employee_id
	validate :salary_date, if: :salary_date?
	

	def salary_date
		if !self.employee_id.nil? && !self.salary_date.nil? && !self.salary_structure_id.nil?
			@employee= Employee.where("id =?",self.employee_id).first
			if (self.salary_date < @employee.date_of_joining)
				errors.add(:salary_date, "Date is invalid. Should not be greater than #{@employee.date_of_joining}")
			end

			@salaries = @employee.employee_salaries

			for salary in @salaries
				if(salary.salary_date.month == self.salary_date.month && salary.salary_date.year == self.salary_date.year)

					errors.add(:salary_date, "Date is invalid. Salary Slip already exsits")
				end
			end
		end
	end
	


end

app/models/leave_head.rb
class LeaveHead < ActiveRecord::Base
	has_many :paymonth_leaves
	has_many :paymonths, through: :paymonth_leaves
end

app/models/paymonth.rb
class Paymonth < ActiveRecord::Base
	has_many :allot_leaves
	has_many :paymonth_leaves
	has_many :leave_heads, through: :paymonth_leaves
	before_save :determine
	validate :months

	def determine
		date = self.pay_month
		self.month_year = @date.year
		self.day_count = Time.days_in_month(self.pay_month.month,self.pay_month.year)
		self.month_name = date.strftime("%b")
		if (Paymonth.where("month_year =? AND month_name =?",self.month_year,self.month_name))
			errors.add(:pay_month, "Pay Month already exsits")
		end
	end

	def months
		date = self.pay_month
		if !(Paymonth.where("month_year =? AND month_name =?",date.year,date.strftime("%b")).empty?)
			errors.add(:pay_month, "Pay Month already exsits")
		end
	end
end

app/models/paymonth_leave.rb
class PaymonthLeave < ActiveRecord::Base
	belongs_to :paymonth
	belongs_to :leave_head
	has_many :employee_leaves
end

app/models/salary_structure.rb
class SalaryStructure < ActiveRecord::Base
	has_many :employee_salaries
	validates_presence_of :name,:basic, :da, :hra, :others,:conveyance, :special_allowance
	#validates_numericality_of :basic, :da, :hra, :others,:conveyance, :special_allowance
	before_save :calculate
	
	def calculate
		@basic_da= self.basic+self.da
		self.pf=(@basic_da*12)/100
		self.emp_pf=(@basic_da*5)/100
		self.gross=self.basic+self.da+self.hra+self.special_allowance+self.others+self.conveyance

		if (self.gross > 15000)
			self.pt=200
			self.gratuity =200
		else
			self.pt=100
			self.gratuity =100
		end
		self.monthly_ctc=self.emp_pf+self.gross+self.pt
	end
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :country
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

	def index
		@departments=Department.all
    @department=Department.new
	end

	def new
		@department=Department.new
	end

	def create
    @department = Department.new(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_path(), notice: 'Department was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  private
  	def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def index
  	@employees=Employee.all
	end

	def new
		@employee=Employee.new
    @states=State.all
	end

  def show
    @employee=Employee.find(params[:id])
    @employee_salaries=@employee.employee_salaries
  end

  def edit
    @employee=Employee.find(params[:id])
  end


	def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path(), notice: 'Employee was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    @employee=Employee.find(params[:id])
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_path, notice: 'Employee was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @employee=Employee.find(params[:id])
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_path, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  	def employee_params
      params.require(:employee).permit(:name, :dob, :gender, :address, :designation_id, :department_id, :date_of_joining, :state,:salary_date)
    end


end

app/helpers/allot_leaves_helper.rb
module AllotLeavesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/designation_helper.rb
module DesignationHelper
end

app/helpers/employee_leaves_helper.rb
module EmployeeLeavesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/leave_heads_helper.rb
module LeaveHeadsHelper
end

app/helpers/paymonth_leaves_helper.rb
module PaymonthLeavesHelper
end

app/helpers/paymonths_helper.rb
module PaymonthsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_exdepartmentation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <%= f.label :Name %>
      <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "Enter Name", required: true %>
  </div>
  <br/>
  <%= f.submit class:"btn btn-info btn-fix"  %>
<%end%>

app/views/departments/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
		  	<div class="panel-heading">Add Department</div>
		  	<div class="panel-body">
		  		<div class="row">
						<div class="col-md-3"></div>
							<div class="col-md-5">
		  					<%=render 'form'%>
		  				</div>
		  			</div>
		  		</div>
		  	</div>
		  </div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
		  	<div class="panel-heading">Departments Employees</div>
		  	<div class="panel-body">
					<div class="table-responsive" style=" width: 100%; margin: 0; overflow-y: auto;">
						<table class="table table-bordered table-hover table-condensed">
							<thead>
								<tr>
									<th>Serial</th>
									<th>Name</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<% @departments.each_with_index do |department,index| %>
										<td><%= index+1 %></td>
										<td><%= department.name%></td>
										<td>
												<%= link_to "Show", department_path(department)%>
												<%= link_to "Edit", edit_department_path(department)%>
												<%= link_to "Delete", department_path(department), method: :delete, data: {confirm: "Are you sure?"} %>
										</td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>	
</div>		

app/views/departments/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="panel panel-info">
		  	<div class="panel-heading">Add Department</div>
		  	<div class="panel-body">
		  		<div class="row">
						<div class="col-md-3"></div>
							<div class="col-md-5">
		  					<%=render 'form'%>
		  				</div>
		  			</div>
		  		</div>
		  	</div>
		  </div>
		</div>
	</div>
</div>