config/routes.rb
Rails.application.routes.draw do

  
  resources :allot_leaves do
    resources :employee_leaves
  end
  resources :leave_heads
  resources :paymonths do 
    resources :paymonth_leaves
  end
  resources :salary_structures
   resources :employees
   resources :departments
   resources :designations
   resources :employee_salaries

  
  root 'employees#index'

end

app/models/allot_leave.rb
class AllotLeave < ActiveRecord::Base
	belongs_to :employee
	belongs_to :paymonth
	has_many :employee_leaves

	validate :checking

	def checking
		if !(AllotLeave.where("employee_id =? AND paymonth_id = ?",self.employee_id, self.paymonth_id).empty? )
			errors.add(:employee_id ,"Leave Structure Already exist for this date")
		end
	end

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :states
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :employees
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/designation.rb
class Designation < ActiveRecord::Base
	has_many :employees
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :allot_leaves
	belongs_to :department
	belongs_to :designation
	has_many :employee_salaries
	validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
	validates_format_of :address, :with => /\A[^`!@#\$%\^&*+_=]+\z/
	validates_presence_of :name,:dob,:address,:designation_id,:department_id,:gender,:state
	validate :validate_birth, if: :date_of_joining?

	def validate_birth
		if  !(self.date_of_joining.nil?)
			if !(self.date_of_joining > self.dob+20.years )
				errors.add(:dob, "Employee should be 20 yesrs old")
			end
			if !(self.date_of_joining < Date.today )
				errors.add(:date_of_joining, "Joining Date should be less than todays date ")
			end
		end

		if (Paymonth.where("month_year =? AND month_name =?",self.salary_date.year,self.salary_date.strftime("%b")).empty?)
			errors.add(:salary_date, "Salary Does not Belong to any Pay month ")
		end
	end
end

app/models/employee_leave.rb
class EmployeeLeave < ActiveRecord::Base
	belongs_to :allot_leave
	belongs_to :paymonth_leave
	validates_presence_of :head_values
end

app/models/employee_salary.rb
class EmployeeSalary < ActiveRecord::Base

	belongs_to :employee
	belongs_to :salary_structure
	validates_presence_of :salary_structure_id,:employee_id
	validate :salary_date, if: :salary_date?
	

	def salary_date
		if !self.employee_id.nil? && !self.salary_date.nil? && !self.salary_structure_id.nil?
			@employee= Employee.where("id =?",self.employee_id).first
			if (self.salary_date < @employee.date_of_joining)
				errors.add(:salary_date, "Date is invalid. Should not be greater than #{@employee.date_of_joining}")
			end

			@salaries = @employee.employee_salaries

			for salary in @salaries
				if(salary.salary_date.month == self.salary_date.month && salary.salary_date.year == self.salary_date.year)

					errors.add(:salary_date, "Date is invalid. Salary Slip already exsits")
				end
			end
		end
	end
	


end

app/models/leave_head.rb
class LeaveHead < ActiveRecord::Base
	has_many :paymonth_leaves
	has_many :paymonths, through: :paymonth_leaves
end

app/models/paymonth.rb
class Paymonth < ActiveRecord::Base
	has_many :allot_leaves
	has_many :paymonth_leaves
	has_many :leave_heads, through: :paymonth_leaves
	before_save :determine
	validate :months

	def determine
		date = self.pay_month
		self.month_year = @date.year
		self.day_count = Time.days_in_month(self.pay_month.month,self.pay_month.year)
		self.month_name = date.strftime("%b")
		if (Paymonth.where("month_year =? AND month_name =?",self.month_year,self.month_name))
			errors.add(:pay_month, "Pay Month already exsits")
		end
	end

	def months
		date = self.pay_month
		if !(Paymonth.where("month_year =? AND month_name =?",date.year,date.strftime("%b")).empty?)
			errors.add(:pay_month, "Pay Month already exsits")
		end
	end
end

app/models/paymonth_leave.rb
class PaymonthLeave < ActiveRecord::Base
	belongs_to :paymonth
	belongs_to :leave_head
	has_many :employee_leaves
end

app/models/salary_structure.rb
class SalaryStructure < ActiveRecord::Base
	has_many :employee_salaries
	validates_presence_of :name,:basic, :da, :hra, :others,:conveyance, :special_allowance
	#validates_numericality_of :basic, :da, :hra, :others,:conveyance, :special_allowance
	before_save :calculate
	
	def calculate
		@basic_da= self.basic+self.da
		self.pf=(@basic_da*12)/100
		self.emp_pf=(@basic_da*5)/100
		self.gross=self.basic+self.da+self.hra+self.special_allowance+self.others+self.conveyance

		if (self.gross > 15000)
			self.pt=200
			self.gratuity =200
		else
			self.pt=100
			self.gratuity =100
		end
		self.monthly_ctc=self.emp_pf+self.gross+self.pt
	end
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :country
end

app/helpers/allot_leaves_helper.rb
module AllotLeavesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/designation_helper.rb
module DesignationHelper
end

app/helpers/employee_leaves_helper.rb
module EmployeeLeavesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/leave_heads_helper.rb
module LeaveHeadsHelper
end

app/helpers/paymonths_helper.rb
module PaymonthsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Payroll</title>
  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

	<!-- Latest compiled and minified Data Tables -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">

<!-- Latest compiled and minified JavaScript Data Tables -->
	<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>

</head>
<body>
<h2 class="header">Relyon Softtech Ltd</h2>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Payroll</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pay Months <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Pay Months", paymonths_path%></li>
            <li><%= link_to "Add Pay Month", new_paymonth_path%></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Employee <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Employee Details", employees_path%></li>
            <li><%= link_to "Add Employee", new_employee_path%></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Salery <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Show Salary Structures", salary_structures_path%></li>
            <li><%= link_to "Add Salary Structures", new_salary_structure_path%></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Leave Details <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Leaves Head" , leave_heads_path%></li>
            <li><%= link_to "Allot Leaves", new_allot_leafe_path%></li>
            <li><%= link_to "Allotted Leaves", allot_leaves_path%></li>
          </ul>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Departments <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Departments", departments_path%></li>
            <li><%= link_to "Add Departments", new_department_path%></li>
          </ul>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Designation <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Designations", designations_path%></li>
            <li><%= link_to "Add Designations", new_designation_path%></li>
          </ul>
        </li>


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Salary Slip <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Salary Listing", employee_salaries_path%></li>
            <li><%= link_to "Generate Salary Slip", new_employee_salary_path%></li>
          </ul>
        </li>

        
      </ul>
    </div>
  </div>
</nav>  
<%= yield %>

</body>
</html>